name: Kubernetes Installation Test

on: 
  pull_request:
    paths:
    - 'kubernetes/**'
  push:
    branches:
    - trigger
    - support-supabase-extensions-and-tables
    paths:
    - 'kubernetes/**'
  workflow_dispatch:

concurrency:
  group: kubernetes-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kubernetes-installation-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v6
    - name: Create Kind Cluster
      uses: helm/kind-action@v1
    - name: Install Spilo
      run: kubectl apply -f kubernetes/spilo_kubernetes.yaml
